name: Advanced Metrics

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: metrics.svg
          token: ${{ secrets.METRICS_TOKEN }}
          user: gufran21
          template: classic
          base: header, activity, community, repositories, metadata
          plugin_languages: yes
          plugin_languages_analysis_timeout: 15
          plugin_habits: yes
          plugin_habits_charts: yes
          plugin_habits_days: 14
          plugin_habits_facts: yes
          plugin_lines: yes
          plugin_followup: yes
          plugin_pagespeed: yes
          plugin_pagespeed_detailed: yes
          plugin_pagespeed_url: https://gufran21.github.io/gufran-portfolio
          plugin_projects: yes
          plugin_stars: yes
          plugin_stars_limit: 4
          plugin_topics: yes
          plugin_topics_limit: 0

  isocalendar:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: metrics.isocalendar.svg
          token: ${{ secrets.METRICS_TOKEN }}
          user: gufran21
          base: ""
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year

  leetcode:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: gufran21/LeetCodeProfileGenerator@main
        with:
          username: WithoutSemicolon # 👈 Replace with your LeetCode username
          theme: github_dark # 👈 Pick any theme (github_dark, dracula, nord, etc.)
          generate_dashboard: 'true'